export const ON_CHANGE_FILTERS = 'ON_CHANGE_FILTERS';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const SET_FIRST_PAGE = 'SET_FIRST_PAGE';
